- name: remove current project dir
  file:
    path: "/applications/friend_trader/"
    state: absent

- name: make project dir
  file:
    path: "/applications/friend_trader/"
    state: directory

- name: make static dir
  file:
    path: "/applications/friend_trader/static/"
    state: directory

- name: make static dir
  file:
    path: "/applications/friend_trader_media/"
    state: directory

- name: unarchive project tar
  unarchive:
    src:  "/tmp/friend_trader.tar"
    dest:  "/"
    copy: True
    list_files: True

- name: install python3 and pip3
  package:
    name:
      - python3-pip
      - python-is-python3
      - python3.10-venv

- name: Make manage.py executable
  file:
    path: /applications/friend_trader/manage.py
    mode: 0777

- name: migrate
  django_manage:
    command: migrate
    arguments: "--verbosity=3"
    app_path: "/applications/friend_trader/"
    settings: "friend_trader.settings.{{ deploy_env }}"
    virtualenv: "/applications/friend_trader/venv"


- name: collect static
  django_manage:
    command: collectstatic
    app_path: "/applications/friend_trader/"
    settings: "friend_trader.settings.{{ deploy_env }}"
    virtualenv: "/applications/friend_trader/venv"

- name: install apache
  package:
    name: 
      - apache2
      - libapache2-mod-wsgi-py3
    state: latest

- name: copy apache config file
  tags: apache,apache3,httpd
  copy:
    src: "{{ apache_config_filename }}"
    dest: "/etc/apache2/sites-available/{{ apache_config_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart_apache

- name: Activate site
  shell: "/usr/sbin/a2ensite {{ apache_config_filename }}"
  notify: Reload Apache

- name: start and enable apache service (Ubuntu)
  tags: apache,httpd
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"