# Generated by Django 4.2.4 on 2023-08-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendtechuser',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
