# Generated by Django 4.2.4 on 2023-08-29 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0002_alter_friendtechuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='KossettoNotFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('blockhash', models.CharField(max_length=255)),
            ],
        ),
    ]
