# Generated by Django 4.2.4 on 2023-08-31 02:43

from django.db import migrations, models
import django.db.models.deletion
import friend_trader_trader.models.share_transaction_base


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0004_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendtechuser',
            name='current_price',
            field=models.DecimalField(decimal_places=25, default=None, max_digits=40, null=True),
        ),
        migrations.CreateModel(
            name='ShareSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='friend_trader_trader.friendtechuser')),
            ],
            bases=(models.Model, friend_trader_trader.models.share_transaction_base.ShareTransactionBase),
        ),
        migrations.CreateModel(
            name='ShareBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='friend_trader_trader.friendtechuser')),
            ],
            bases=(models.Model, friend_trader_trader.models.share_transaction_base.ShareTransactionBase),
        ),
    ]
