# Generated by Django 4.2.4 on 2023-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0005_friendtechuser_share_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_hash',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
