# Generated by Django 4.2.4 on 2023-08-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0005_friendtechuser_current_price_sharesell_sharebuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendtechuser',
            name='share_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='friendtechuser',
            name='twitter_followers',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
