# Generated by Django 4.2.4 on 2023-09-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0006_alter_block_block_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareprice',
            name='current_price',
        ),
        migrations.AddField(
            model_name='shareprice',
            name='block',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='friend_trader_trader.block'),
        ),
        migrations.AddField(
            model_name='shareprice',
            name='buy_price',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='shareprice',
            name='sell_price',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=45, null=True),
        ),
    ]
