# Generated by Django 4.2.4 on 2023-09-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0007_remove_shareprice_current_price_shareprice_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
    ]
