# Generated by Django 4.2.4 on 2023-09-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0008_remove_transaction_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendtechuser',
            old_name='share_count',
            new_name='shares_supply',
        ),
        migrations.AddField(
            model_name='friendtechuser',
            name='last_online',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
