# Generated by Django 4.2.4 on 2023-09-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0009_rename_share_count_friendtechuser_shares_supply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('buyShares', 'BUY'), ('sellShares', 'SELL')], max_length=20),
        ),
    ]
