# Generated by Django 4.2.4 on 2023-09-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0012_shareprice_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy', models.BooleanField(default=False)),
                ('share_amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=20, max_digits=45)),
                ('protocol_fee', models.DecimalField(decimal_places=20, default=None, max_digits=45, null=True)),
                ('subject_fee', models.DecimalField(decimal_places=20, default=None, max_digits=45, null=True)),
                ('supply', models.IntegerField()),
                ('hash', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='friend_trader_trader.block')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_prices', to='friend_trader_trader.friendtechuser')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='friend_trader_trader.friendtechuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='block',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='friend_tech_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_from',
        ),
        migrations.DeleteModel(
            name='SharePrice',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
