# Generated by Django 4.2.4 on 2023-09-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0013_trade_remove_transaction_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='hash',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
