# Generated by Django 4.2.4 on 2023-09-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0014_alter_trade_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=20, max_digits=45)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='friend_trader_trader.trade')),
            ],
        ),
    ]
