# Generated by Django 4.2.4 on 2023-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0016_alter_trade_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendtechuser',
            name='holder_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='friendtechuser',
            name='holding_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='friendtechuser',
            name='twitter_profile_banner',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='friendtechuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
