# Generated by Django 4.2.4 on 2023-10-04 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend_trader_trader', '0018_friendtechuser_latest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendtechuser',
            name='latest_price',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_price', to='friend_trader_trader.price'),
        ),
    ]
