# Generated by Django 4.2.4 on 2023-10-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend_trader_trader', '0019_alter_friendtechuser_latest_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendTechUserWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend_tech_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_trader_trader.friendtechuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friendtechuser',
            name='watchers',
            field=models.ManyToManyField(related_name='watchlist', through='friend_trader_trader.FriendTechUserWatchList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='friendtechuserwatchlist',
            constraint=models.UniqueConstraint(fields=('user', 'friend_tech_user'), name='unique_user_friendtechuser'),
        ),
    ]
